services:
  ubuntu-ssh:
    image: registry.cn-beijing.aliyuncs.com/xiaozhu245/ubuntu_ssh:latest
    container_name: ubuntu24
    init: true

    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD:-<替换密码>}
      - SSH_PORT=${SSH_PORT:-2222}

    network_mode: host

    privileged: true
    user: "0:0"
    restart: always
    stop_signal: SIGTERM
    stop_grace_period: 15s

    volumes:
      - type: bind
        source: /
        target: /host-root
        bind:
          propagation: rslave
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /run/dbus/system_bus_socket

    healthcheck:
      test: ["CMD-SHELL", "ss -ltn | grep -q \":${SSH_PORT:-2222} \" || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
