services:
  ubuntu-ssh:
    image: registry.cn-beijing.aliyuncs.com/xiaozhu245/ubuntu_ssh:latest
    container_name: ubuntu24

    environment:
      ROOT_PASSWORD: ${ROOT_PASSWORD:?ROOT_PASSWORD is required}
      SSH_PORT: ${SSH_PORT:-2222}

    network_mode: host

    privileged: true
    user: "0:0"
    restart: unless-stopped

    pid: host
    ipc: host
    uts: host
    cgroup: host

    volumes:
      - type: bind
        source: /
        target: /host-root
        bind:
          propagation: rslave
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /run/dbus/system_bus_socket
      - type: bind
        source: /var/run
        target: /var/run

    healthcheck:
      test: ["CMD-SHELL", "ss -ltn | grep -q \":${SSH_PORT:-2222} \" || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
